md <- read.csv(file="C:/Users/Dharit/Documents/Data/ATvIHDI_1.csv", strip.white=TRUE, header=TRUE)
mi <- min(md$HDI)
ma <- max(md$HDI)
md$normHDI=(md$HDI - mi)/(ma - mi)
miT <- min(md$AT)
maT <- max(md$AT)
md$normAT=(md$AT - miT)/(maT - miT)
md$modHDI <- 10*(md$normHDI)
library(countrycode)
md$CCode<-countrycode(md$Country,"country.name","iso3c")
md$R <- md$normAT*255
md$B <- (255-(md$normAT*255))
#dimple(md, xMeasure="normAT", yMeasure="normHDI", series="Country", chartType="bubble")
library(rworldmap)
mapDevice()
mmd <- joinCountryData2Map(md, joinCode="ISO3", nameJoinColumn="CCode", nameCountryColumn = "Country", suggestForFailedCodes = FALSE, mapResolution="coarse", projection=NA, verbose = FALSE)
#mapCountryData( mmd, nameColumnToPlot="HDI")
#barplotCountryData( mmd, nameColumnToPlot="AT", nameCountryColumn = "Country")
mapBubbles(mmd, nameZSize = "modHDI", nameZColour = "normAT", symbolSize = 0.5, main = "HDIvAT", colourPalette = c('red','white','blue'), mapRegion = "world", borderCol = "black", addLegend = FALSE, addColourLegend = FALSE)
	   